# Generated by Django 4.0 on 2022-05-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edutech_app', '0003_alter_course_description_alter_teacher_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classnumber',
            old_name='Number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Name',
            new_name='name',
        ),
    ]
