# Generated by Django 4.0 on 2022-05-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutech_app', '0004_rename_number_classnumber_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description1',
            field=models.TextField(default='a', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description2',
            field=models.TextField(default='a', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description3',
            field=models.TextField(default=1, max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='header1',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='header2',
            field=models.TextField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='header3',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
