# Generated by Django 4.0 on 2022-05-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edutech_app', '0005_course_description1_course_description2_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
