# Generated by Django 4.0 on 2022-06-03 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edutech_app', '0007_rename_с_classnumber_currentcourse_c_classnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcourse',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edutech_app.user'),
            preserve_default=False,
        ),
    ]
