# Generated by Django 4.0 on 2022-05-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutech_app', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('classNumber', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
