# Generated by Django 4.0 on 2022-06-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutech_app', '0008_currentcourse_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentcourse',
            name='user',
        ),
        migrations.AddField(
            model_name='currentcourse',
            name='username',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
