# Generated by Django 4.0 on 2022-06-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edutech_app', '0009_remove_currentcourse_user_currentcourse_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentcourse',
            old_name='username',
            new_name='c_username',
        ),
    ]
