# Generated by Django 4.0 on 2022-06-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutech_app', '0011_alter_currentcourse_c_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentcourse',
            name='c_username',
            field=models.TextField(),
        ),
    ]
