# Generated by Django 4.0 on 2022-06-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edutech_app', '0013_rename_c_username_currentcourse_c_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentcourse',
            old_name='c_email',
            new_name='email',
        ),
    ]
