# Generated by Django 4.0 on 2022-06-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edutech_app', '0014_rename_c_email_currentcourse_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='classNumber',
            new_name='class_number',
        ),
    ]
