# Generated by Django 4.0 on 2022-06-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edutech_app', '0015_rename_classnumber_course_class_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentcourse',
            old_name='c_classNumber',
            new_name='class_number',
        ),
    ]
