# Generated by Django 4.0 on 2022-06-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edutech_app', '0016_rename_c_classnumber_currentcourse_class_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentcourse',
            old_name='c_course_id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='currentcourse',
            old_name='c_name',
            new_name='name',
        ),
    ]
